name: Snes9xFX Build

on: workflow_dispatch
jobs:
  build:
    name: Build Snes9xFX
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["Wii"]
    container: devkitpro/devkitppc:20230110
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build Wii
      if: ${{ matrix.image == 'Wii' }}
      run: |
        make -f Makefile.wii -j2
    
    - name: Copy Wii artifact
      if: ${{ matrix.image == 'Wii' }}
      run: | 
        mkdir -p dist/Snes9xFX/apps/snes9xfx
        mkdir -p dist/Snes9xFX/snes9xfx/roms
        mkdir dist/Snes9xFX/snes9xfx/cheats
        mkdir dist/Snes9xFX/snes9xfx/saves
        mkdir dist/Snes9xFX/snes9xfx/satdata
        touch dist/Snes9xFX/snes9xfx/roms/romsdir
        touch dist/Snes9xFX/snes9xfx/cheats/cheatsdir
        touch dist/Snes9xFX/snes9xfx/saves/savesdir
        touch dist/Snes9xFX/snes9xfx/satdata/satdatadir
        cp hbc/* dist/Snes9xFX/apps/snes9xfx/
        cp executables/snes9xfx-wii.dol dist/Snes9xFX/apps/snes9xfx/boot.dol

    - name: Upload Wii artifacts
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'Wii' }}
      with: 
        name: Snes9xFX
        path: |
         dist/Snes9xFX/
